// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Buscador', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Buscador', async function() {
    // Test name: Buscador
    // Step # | name | target | value
    // 1 | open | /wiki/Wikipedia:Portada | 
    await driver.get("https://es.wikipedia.org/wiki/Wikipedia:Portada")
    // 2 | type | id=searchInput | Software
    await driver.findElement(By.id("searchInput")).sendKeys("Software")
    // 3 | click | id=searchButton | 
    await driver.findElement(By.id("searchButton")).click()
    // 4 | assertText | id=firstHeading | Software
    assert(await driver.findElement(By.id("firstHeading")).getText() == "Software")
  })
})
