// Generated by Selenium IDE
/*
const { Builder, By, Key, until } = require('selenium-webdriver')
var assert = require("chai").assert;

describe('Buscador', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Buscador', async function() {
    // Test name: Buscador
    // Step # | name | target | value
    // 1 | open | /wiki/Wikipedia:Portada |
    await driver.get("https://cursosdedesarrollo.com/")
    // 2 | type | id=searchInput | Software
    await driver.findElement(By.id("wp-block-search__input-1")).sendKeys("nas")
    // 3 | click | id=searchButton |
    await driver.findElement(By.css("button.wp-block-search__button.wp-element-button")).click()
    // 4 | assertText | id=firstHeading | Software
    let headerText = await driver.findElement(By.css("header.page-header h1")).getText();
    assert.include(headerText, "nas", 'array not contains value');
  })
})
*/