// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver';
import {paginaBusqueda} from './pages/paginaBusqueda.js';
import {paginaResultados} from './pages/paginaResultados.js';
import { assert } from 'chai';

describe('navegacion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('navegacion', async function() {

    // Test name: navegacion
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get(paginaBusqueda.url)
    // 2 | setWindowSize | 1920x1080 | 
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    // 3 | type | id=wp-block-search__input-1 | nas
    await paginaBusqueda.searchInput(driver).sendKeys("nas")
    // 4 | click | css=.wp-block-search__button |
    await paginaBusqueda.searchButton(driver).click()
    // 5 | assertText | css=header.page-header h1 | Search results for: nas
    assert(await paginaResultados.searchTitle(driver).getText() == "Search results for: nas")
  })
})
