// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const pagina = require("./pages/paginaBusqueda");
const {searchButton} = require("./pages/paginaBusqueda");
var assert = require("chai").assert;
var paginaBusqueda = require("./pages/paginaBusqueda");
var paginaResultados = require("./pages/paginaResultados");

describe('navegacion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('navegacion', async function() {

    // Test name: navegacion
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get(paginaBusqueda.url)
    // 2 | setWindowSize | 1920x1080 | 
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    // 3 | type | id=wp-block-search__input-1 | nas
    await paginaBusqueda.searchInput(driver).sendKeys("nas")
    // 4 | click | css=.wp-block-search__button |
    await paginaBusqueda.searchButton(driver).click()
    // 5 | assertText | css=header.page-header h1 | Search results for: nas
    assert(await paginaResultados.searchTitle(driver).getText() == "Search results for: nas")
  })
})
